language: ruby
rvm:
  - 1.8.7
  - 1.9.3
matrix:
  allow_failures:
    - env: TEST_SUITE="spec"
bundler_args: --without development
# FIXME Get the code to automatically create queue.lock so we don't have to
#       touch it here or keep it in git
before_script: 'mkdir -p tmp; touch tmp/queue.lock; mkdir -p log'
env:
  - TEST_SUITE="test:units"
  - TEST_SUITE="spec"
  - TEST_SUITE="test:units spec"
script: 'rake db:drop db:migrate db:fixtures:dump $TEST_SUITE'
notifications:
  email:
    - crowbar@dell.com
  irc:
    on_success: change
    on_failure: always
    channels:
      - irc.freenode.org#crowbar
